In [1]:
import numpy as np
import numpy.linalg as la ## used for linear algebra things like inverse matrix, etc.

In [2]:
a = np.array([[1,2], [3,4]], dtype="i") 

In [3]:
print(a)

[[1 2]
 [3 4]]


# Dtype and Dimensions

In [4]:
a.dtype # shows the type the array holds 

dtype('int32')

In [5]:
a.ndim # shows how many dimensions the array has

2

#### *If you want to create a multi-dimensional array (like a 2D array), all the inner arrays must have the same number of elements.*

#### *For unequal number of elements just set dtype = object*


In [6]:
# Example of code that doesn't work when the inner arrays have an unequal number of elements.
# b = np.array([[1,2], [1, 2, 3]])
# b.ndim

In [ ]:
c = np.array([[[1,2], [54, 56]], [[50, 40], [30, 20]]])
print(c[0,1,1]) # Indexes can be listed using commas, one after another

56


# Shape and Size

In [8]:
print(c.shape)  # Returns a tuple representing the array dimensions: (2D arrays, 1D arrays, elements per 1D array)
print(c.shape[0]) # Retrieves the first dimension from the shape tuple (number of 2D arrays)

(2, 2, 2)
2


In [9]:
c.size # shows how many elements are in the whole array

8

# Arrange, Random, and Reshape

In [10]:
a = np.arange(20, 100) # create an array with values from a to b-1  [or just from 0 to a, if b not given]
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
a = np.arange(20, 100, 3) # can make it with a jump of three
a

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68,
       71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [12]:
b = np.random.permutation(a) # rearranges all values in a random fashion
b

array([20, 23, 92, 38, 65, 98, 83, 68, 41, 59, 44, 50, 47, 89, 56, 95, 62,
       71, 26, 86, 29, 74, 77, 32, 80, 35, 53])

#### *Can create random numbers on .random with .rand() or .randn()*

#### *Can use np.zeros and np.ones to create arrays with zeroes or ones* 

In [13]:
c = np.arange(100).reshape(4, 25) # makes the array into a 2-dimensional array with 4 subarrays, with 25 elements each.
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

# Slicing and Sorting

#### *When you create a slice from something, the slice doesn’t make a copy of the data. Instead, it points to the same memory location as the original. This means that if you modify the slice, you’re also changing the original data.*

In [14]:
D = np.arange(100)

print(D[3:10]) ## from 3 to 9

print(D[::5]) ## every fifth element

print(D[::-5]) ## every fifth element from the end 


print()


E = np.round(10*np.random.rand(5,4))

print(E[:, 1:3]) ## returns a submatrix with all rows and sliced columns

print(E[1:3, 1:3]) ## returns a submatrix with slicing

[3 4 5 6 7 8 9]
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[99 94 89 84 79 74 69 64 59 54 49 44 39 34 29 24 19 14  9  4]

[[6. 3.]
 [6. 2.]
 [6. 9.]
 [7. 4.]
 [9. 4.]]
[[6. 2.]
 [6. 9.]]


#### *[::5] means “take every 5th element from start to end, without specifying a start or end index."*

#### *":" means everything*

In [15]:
print(E)

print()

print(E.T) ## creates a transpose

[[5. 6. 3. 7.]
 [9. 6. 2. 6.]
 [2. 6. 9. 5.]
 [9. 7. 4. 8.]
 [7. 9. 4. 5.]]

[[5. 9. 2. 9. 7.]
 [6. 6. 6. 7. 9.]
 [3. 2. 9. 4. 4.]
 [7. 6. 5. 8. 5.]]


In [16]:
E.sort(axis=0) ## sorts the columns with axis = 1, it sorts the rows (affects the original array, works for more dimensions)
E

array([[2., 6., 2., 5.],
       [5., 6., 3., 5.],
       [7., 6., 4., 6.],
       [9., 7., 4., 7.],
       [9., 9., 9., 8.]])

#### *.sort() can be used on 1-dimensional arrays, just don't give it an axis.*

# Masking and Broadcasting

#### *Makes a copy of the data, so it doesn't change the original*

In [17]:
F = np.arange(20, 25)

## using indexing with double [] -> F[index_array]
print(F[[0, 3, 4]]) ## can get specific indexes

print(F[[True, False, True, False, False]]) ## use True/False list to filter data, returns only True positions.

## using conditions F[F<8]
print(F[F<23]) ## filters all that are below 23

[20 23 24]
[20 22]
[20 21 22]


#### *Can use &, 'and' in the conditions. & - used for arrays, 'and' used for single objects.*

In [18]:
G = np.arange(40, 60).reshape(2, 10)
print(G + 5) ## adds five to all columns of the matrix, for any dimensional matrix (can even add arrays this way)

Z = np.arange(2, 8).reshape(2, 3)
W = np.arange(14, 20).reshape(2, 3)

print()

print(np.hstack((Z,W))) ## concats two arrays horizontally

print()

print(np.vstack((Z,W))) ## concats two arrays vertically

[[45 46 47 48 49 50 51 52 53 54]
 [55 56 57 58 59 60 61 62 63 64]]

[[ 2  3  4 14 15 16]
 [ 5  6  7 17 18 19]]

[[ 2  3  4]
 [ 5  6  7]
 [14 15 16]
 [17 18 19]]


#### *Can use .concatenate() for joining on existing axis*

In [19]:
import pandas as pd

# Pandas Series and DataFrames

In [20]:
A = pd.Series([1,2,3,4,5], index=["a", "b", "c", "d", "e"]) ## just an array, can make custom indexes
print(A)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [21]:
print(A.values)
print(A.index)

[1 2 3 4 5]
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


#### *For explicit indexing, it includes the final element too. (indexing works the same as numpy)*

#### *Can create a series with a dictionary, just pass it to pd.Series()*

In [22]:
A = pd.Series([1,2,3,4,5], index=["a", "b", "c", "d", "e"]) 
B = pd.Series([10, 15, 25, 35, 600])

C = pd.DataFrame[{"A": A, "B": B}]

TypeError: type 'DataFrame' is not subscriptable